# Base image
FROM python:3.8.5-slim-buster

# set base dir
WORKDIR /usr/app/src

# Copy files
COPY . /src

# Install dependencies
RUN pip install -r /src/requirements.txt

# start the api
CMD [ "python3", "/src/api.py"]
